#!/usr/bin/env python3
"""Generate the conformance scores T0-T11 from skeinsim.py's own random
machines (same seeds), so that the Rust suite exercises the same machines as
the reference simulator.  Run from this directory:

    python3 gen_scores.py /path/to/publications/f1r3score
"""
import os, random, sys
sys.path.insert(0, sys.argv[1] if len(sys.argv) > 1 else '../../../publications/f1r3score')
from skeinsim import random_machine

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'scores')
CHROM = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
def names(n):          # n ordered pitches from C4 upward, chromatically
    return [CHROM[i % 12] + str(4 + i // 12) for i in range(n)]
DURS = [('w', '1'), ('h', '1/2'), ('q', '1/4'), ('e', '1/8'), ('s', '1/16')]

def header(title, n_ordered, rest_last=True, timbres='piano = gm(0) on 1'):
    P = names(n_ordered)
    ps = P + ['r'] if rest_last else ['r'] + P
    return (f"// {title}\n// generated by gen_scores.py from skeinsim.py's machines; do not edit\n"
            "import std\n"
            f"pitches {{ {', '.join(ps)} }}\n"
            f"durations {{ {', '.join(f'{a} = {b}' for a, b in DURS)} }}\n"
            f"timbres {{ {timbres} }}\n"), P + ['r']

def w(x):
    return str(x) if not isinstance(x, float) or x != int(x) else str(int(x))

def machine(kind, E, states, dual=False):
    arrows = ', '.join(f"{states[s]} -> {states[t]} @ {w(v)}" for (s, t), v in sorted(E.items()))
    return f"machine {kind}{' dual' if dual else ''} {{ {arrows} }}"

D = [a for a, _ in DURS]

def write_machines(name, parts):
    """Plain-text copy of the machines for the statistical tests:
    `KIND s t w` lines with state indices."""
    with open(os.path.join(OUT, name), 'w') as f:
        for kind, E in parts:
            for (a, b), v in sorted(E.items()):
                f.write(f"{kind} {a} {b} {w(v)}\n")

def write(name, text):
    with open(os.path.join(OUT, name), 'w') as f:
        f.write(text)

def voice_score(fname, title, rng_seed, deg_d=(1, 3), ep_deg=(2, 4)):
    rng = random.Random(rng_seed)
    EP, ED = random_machine(16, rng, ep_deg), random_machine(5, rng, deg_d)
    h, S = header(title, 15)
    write(fname, h +
          f"factor style = {machine('pitch', EP, S)}\n"
          f"factor rhythm = {machine('dur', ED, D)}\n"
          f"play Voice(piano, style * rhythm, {S[0]}, q, \"A\") #A\n")
    write_machines(fname.replace('.score', '.machines'), [('pitch', EP), ('dur', ED)])
    return EP, ED

# T0 and T11 use Random(1); T1 uses Random(7) with (2,3) duration degree
voice_score('t0_inertness.score', 'T0: inertness of the unplayed', 1)
voice_score('t1_law.score', 'T1: the law of one voice (pitch leads)', 7, (2, 3))
voice_score('t11_reflective_inert.score', 'T11: reflective voice, the unplayed is inert', 1, (2, 3))

# T2: two voices sharing a timbre, streams by label
r0 = random.Random(3)
EA, EDA = random_machine(16, r0), random_machine(5, r0, (1, 3))
EB, EDB = random_machine(16, r0), random_machine(5, r0, (1, 3))
h, S = header('T2: harmony by independence', 15)
write('t2_harmony.score', h +
      f"factor styleA = {machine('pitch', EA, S)}\nfactor rhythmA = {machine('dur', EDA, D)}\n"
      f"factor styleB = {machine('pitch', EB, S)}\nfactor rhythmB = {machine('dur', EDB, D)}\n"
      f"play Voice(piano, styleA * rhythmA, {S[0]}, q, \"A\") #A\n"
      f"   | Voice(piano, styleB * rhythmB, {S[7]}, h, \"B\") #B\n")

# T3: two-sided fitting, m = 3 hands and n = 4 duration messages at one location
h, S = header('T3: a note cannot be fitted from both sides', 15)
hands = ' | '.join(f"for (_ <- <@base \"K\", piano, {S[i]}>) {{ 0 }}" for i in range(3))
msgs = ' | '.join(f"<@base \"K\", piano, {D[j]}>!(base \"q{j}\", piano, {S[0]})" for j in range(4))
write('t3_two_sided.score', h + f"play {hands}\n   | {msgs}\n")

# T4: the embedding -- uniform machines, pi drives pitch in base 16, e drives
# duration in base 5; the rest is the last pitch state as on the instrument
h, S = header('T4: embedding of the spigot instrument', 15, rest_last=True)
write('t4_embedding.score', h.replace('pitches {', 'pitches {', 1) +
      "play Voice(piano, machine pitch uniform * machine dur uniform, D4, w, \"A\") #A\n")

# T5: the dual (rhythm leads)
rng = random.Random(7)
EP, ED = random_machine(16, rng), random_machine(5, rng, (2, 3))
h, S = header('T5: the law of the dual (rhythm leads)', 15)
write('t5_dual.score', h +
      f"factor style = {machine('pitch', EP, S, dual=True)}\n"
      f"factor rhythm = {machine('dur', ED, D, dual=True)}\n"
      f"play DualVoice(piano, style * rhythm, {S[0]}, q, \"A\") #A\n")
write_machines('t5_dual.machines', [('pitch', EP), ('dur', ED)])

# T6: two hands at one location, five duration messages, constant clause
h, S = header('T6: simultaneity by contention', 15)
hands = ' | '.join(f"for (_ <- <@base \"shared\", piano, {S[i]}>) {{ 0 }}" for i in (0, 4))
msgs = ' | '.join(f"<@base \"shared\", piano, {D[j]}>!(base \"q{j}\", piano, {S[0]})" for j in range(5))
write('t6_coupled.score', h + f"play {hands}\n   | {msgs}\n")

# T7: style (x) physicality over 21 ordered pitches, durations {q, e} only
rng = random.Random(21)
style = random_machine(21, rng, (4, 7))
h, S = header('T7: style (x) physicality', 21)
ED7 = {(u, v): 1 for u in range(5) for v in (2, 3)}
for name, rule in (('stepwise', '-2..2: 3'), ('leaping', '-7: 3, -4: 3, 4: 3, 7: 3')):
    write(f't7_{name}.score', h +
          f"factor style = {machine('pitch', style, S)}\n"
          f"factor phys = table step {{ {rule}, _: 3/10 }}\n"
          f"factor rhythm = {machine('dur', ED7, D)}\n"
          f"play Voice(piano, style * phys * rhythm, {S[0]}, q, \"A\") #A\n")
write_machines('t7.machines', [('pitch', style)])

# T8: idioms read from the past
rng = random.Random(33)
EP, ED = random_machine(16, rng, (3, 5)), random_machine(5, rng, (2, 3))
EP2 = dict(EP); EP2[(0, 2)] = EP2.get((0, 2), 1); EP2[(2, 4)] = EP2.get((2, 4), 1)
EP2[(2, 2)] = EP2.get((2, 2), 1); EP2[(5, 5)] = 3
h, S = header('T8: idioms read from the past', 15)
base = f"factor style = {machine('pitch', EP2, S)}\nfactor rhythm = {machine('dur', ED, D)}\n"
forbid = "factor forbid = [!(any t in pitches { back(0, t) && back(1, t) && carry(t) })]\n"
boost = f"factor boost = [back(1, {S[0]}) && back(0, {S[2]}) && carry({S[4]})] * 20 + 1\n"
for name, extra, psi in (('unconstrained', '', 'style * rhythm'),
                         ('forbid', forbid, 'style * rhythm * forbid'),
                         ('motif', boost, 'style * rhythm * boost')):
    write(f't8_{name}.score', h + base + extra + f"play Voice(piano, {psi}, {S[0]}, q, \"A\") #A\n")

# T10: reflective voice vs an unrolled voice of K written steps, same clause
rng0 = random.Random(7)
EP, ED = random_machine(16, rng0), random_machine(5, rng0, (2, 3))
h, S = header('T10: reflective voice = constant voice', 15)
common = h + f"factor psi = {machine('pitch', EP, S)} * {machine('dur', ED, D)}\n"
write('t10_reflective.score', common + f"play Voice(piano, psi, {S[0]}, q, \"A\") #A\n")
K = 600
defs = "def U0(w: name) = 0\n" + ''.join(
    f"def U{i}(w: name) = Step(w, piano, psi, U{i-1}(_))\n" for i in range(1, K + 1))
write('t10_unrolled.score', common + defs +
      f"play U{K}(<@Seed(base \"A\", piano, {S[0]}, q), piano, r>) #A\n")
print('wrote scores to', OUT)
